#!/bin/bash

# -----------------------------------------------------------------------------
# extra for jibri-school-installer
# -----------------------------------------------------------------------------
PROSODY=/etc/prosody/conf.avail/$JITSI_HOST.cfg.lua
JICOFO_SIP=/etc/jitsi/jicofo/sip-communicator.properties
JITSI_MEET_CONFIG=/etc/jitsi/meet/$JITSI_HOST-config.js
JITSI_MEET_INTERFACE=/usr/share/jitsi-meet/interface_config.js


# -----------------------------------------------------------------------------
# prosody
# -----------------------------------------------------------------------------
out <<< "installing jitsi-meet-tokens for school use..."

APPSECRET=$(openssl rand -hex 40)

max=""
for w in $(echo $JITSI_HOST | tr '.' ' '); do
    [[ ${#w} -gt ${#max} ]] && max=$w;
done
APPID=$max

debconf-set-selections <<< \
    "jitsi-meet-tokens jitsi-meet-tokens/appid string $APPID"
debconf-set-selections <<< \
    "jitsi-meet-tokens jitsi-meet-tokens/appsecret password $APPSECRET"
apt-get $APT_PROXY_OPTION -y install jitsi-meet-tokens

sed -i '/allow_empty_token/d' $PROSODY
sed -i '/token_affiliation/d' $PROSODY
sed -i '/token_owner_party/d' $PROSODY
sed -i '/\s*app_secret=/a \    allow_empty_token = false' $PROSODY
sed -i '0,/\s*"token_verification"/!b; /\s*"token_verification"/a \
\    "token_affiliation";' $PROSODY
sed -i '0,/\s*"token_affiliation"/!b; /\s*"token_affiliation"/a \
\    "token_owner_party";' $PROSODY

systemctl restart prosody.service

# token is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-school-token" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jicofo
# -----------------------------------------------------------------------------
out <<< "configuring jicofo for school use..."

sed -i "/org.jitsi.jicofo.DISABLE_AUTO_OWNER/ s/^#//" $JICOFO_SIP

systemctl restart jicofo.service
systemctl restart jitsi-videobridge2.service

# jicofo customization is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-school-jicofo" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jitsi-meet
# -----------------------------------------------------------------------------
out <<< "configuring jitsi-meet for school use..."

sed -i "/startWithAudioMuted:/ s~//\s*~~" $JITSI_MEET_CONFIG
sed -i "/startWithAudioMuted:/ s~:.*~: false,~" $JITSI_MEET_CONFIG
sed -i "/startWithVideoMuted:/ s~//\s*~~" $JITSI_MEET_CONFIG
sed -i "/startWithVideoMuted:/ s~:.*~: true,~" $JITSI_MEET_CONFIG
sed -i "/channelLastN:/ s~//\s*~~" $JITSI_MEET_CONFIG
sed -i "/channelLastN:/ s~:.*~: 4,~" $JITSI_MEET_CONFIG
sed -i "/disableProfile:/ s~//\s*~~" $JITSI_MEET_CONFIG
sed -i "/disableProfile:/ s~:.*~: true,~" $JITSI_MEET_CONFIG
sed -i "/enableFeaturesBasedOnToken:/ s~//\s*~~" $JITSI_MEET_CONFIG
sed -i "/enableFeaturesBasedOnToken:/ s~:.*~: true,~" $JITSI_MEET_CONFIG

# meet customization is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-school-meet" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jitsi-meet interface
# -----------------------------------------------------------------------------
out <<< "configuring jitsi-meet interface for school use..."

sed -i "/^\s*DISABLE_JOIN_LEAVE_NOTIFICATIONS:/ s/:.*/: true,/" \
    $JITSI_MEET_INTERFACE
sed -i "s/'sharedvideo'/''/" $JITSI_MEET_INTERFACE
sed -i "s/'videobackgroundblur'/''/" $JITSI_MEET_INTERFACE

# interface customization is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-school-interface" \
    >/dev/null || true

# -----------------------------------------------------------------------------
# jitsi-meet static
# -----------------------------------------------------------------------------
out <<< "configuring jitsi-meet static files for school use..."

wget -O /usr/share/jitsi-meet/body.html \
    $JITSI_TMPL/usr/share/jitsi-meet/body.school.html
wget -O /usr/share/jitsi-meet/static/authError.html \
    $JITSI_TMPL/usr/share/jitsi-meet/static/authError.school.html
sed -i "s/___JITSI_HOST___/$JITSI_HOST/" /usr/share/jitsi-meet/body.html
sed -i "s/___JITSI_HOST___/$JITSI_HOST/" \
    /usr/share/jitsi-meet/static/authError.html

# static customization is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-school-static" \
    >/dev/null || true

# -----------------------------------------------------------------------------
# JWT tools
# -----------------------------------------------------------------------------
apt-get $APT_PROXY_OPTION -y install php-cli composer

cd /tmp
rm -rf /tmp/vendor
composer -qn require firebase/php-jwt
cd -

mkdir -p /root/jwt
cp -arp /tmp/vendor /root/jwt/
wget -O /root/jwt/README.md $TOOLS/jitsi/jwt/README.md
wget -O /root/jwt/teacher.php $TOOLS/jitsi/jwt/teacher.php
wget -O /root/jwt/student.php $TOOLS/jitsi/jwt/student.php

sed -i "s/___JITSI_HOST___/$JITSI_HOST/" /root/jwt/teacher.php
sed -i "s/___APPSECRET___/$APPSECRET/" /root/jwt/teacher.php
sed -i "s/___APPID___/$APPID/" /root/jwt/teacher.php

sed -i "s/___JITSI_HOST___/$JITSI_HOST/" /root/jwt/student.php
sed -i "s/___APPSECRET___/$APPSECRET/" /root/jwt/student.php
sed -i "s/___APPID___/$APPID/" /root/jwt/student.php

# JWT tools are ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-school-jwt" \
    >/dev/null || true

# -----------------------------------------------------------------------------
# completed
# -----------------------------------------------------------------------------
# school completed
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-school" \
    >/dev/null || true

out <<EOF
YOUR APP ID: $APPID
YOUR APP SECRET: $APPSECRET
EOF
